mod atomic_pointer_state;
pub(crate) mod classify;
mod copy_operation;
pub(crate) mod evidence;
mod ffi_boundary;
mod maybeuninit_operation;
pub(crate) mod obligations;
pub(crate) mod pipeline;
pub(crate) mod receipts;
pub(crate) mod scanner;
mod set_len_shrink;
mod slice_operation;
mod static_mut;
pub(crate) mod syntax;
mod target_feature;
mod unsafe_impl;
mod vec_operation;
pub(crate) mod witness;
