//! Generated production code. Generated origin does not exempt a seam
//! from production review work.
//!
//! @generated by mixed-source-roles codegen. Do not edit.

/// Generated production seam: unchecked indexing helper.
pub fn generated_get(buf: &[u8], idx: usize) -> u8 {
    unsafe { *buf.get_unchecked(idx) }
}
